### ISSUE TITLE
Add sign in (with account features like uploading liking commenting subscribing purchases etc), Return YouTube Dislike's API for dislikes and

### ISSUE THREAD

**Issue by SGR21gtb** [kendoodoo/tuberepair-python#7]

**Comment by SGR21gtb** [comment]
oh I forgot umm channel activity and more categories in homepage (like Music Comedy Entertainment etc) and all music videos when possible and how is suggested videos working? I saw it on reddit today

**Comment by kendoodoo** [comment]
You have to know that building the login function takes months for us to figure this out (Big thanks to Requis), and YouTube fights back, a lot. That's why the "Client ID" error exists on old versions of the tweak. Basically we gave up. Doing implementation straight from innerTube (Which is the response for custom feed straight from YouTube private API) will eat server bandwidth.

**Comment by kendoodoo** [comment]
But hey, if you can contribute, gooooo. I think you're familiar with yt2009 source code because I borrow them a lot.

**Comment by SGR21gtb** [comment]
> But hey, if you can contribute, gooooo. I think you're familiar with yt2009 source code because I borrow them a lot.

No thanks, sadly.

**Comment by SGR21gtb** [comment]
> You have to know that building the login function takes months for us to figure this out (Big thanks to Requis), and YouTube fights back, a lot. That's why the "Client ID" error exists on old versions of the tweak. Basically we gave up. Doing implementation straight from innerTube (Which is the response for custom feed straight from YouTube private API) will eat server bandwidth.

damn, but try hard

**Comment by SGR21gtb** [comment]
I dislike YouTube signed out on old devices :(

**Comment by SGR21gtb** [comment]
How about live video, captions, video qualities in-app, channel activity, more categories support (Entertainment, Music, People & Blogs etc) and app support up to 2.2.0 (1.0.0, 1.0.1, 1.1.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 2.0.0, 2.1.0 and 2.2.0 along with betas)? Optionally, VEVO branding.

**Comment by kendoodoo** [comment]
You prefer your tube signed in, go do it.
